name: Build and Analyze

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
